name: Build and Test JMeter GUI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show working directory contents
        run: ls -alh

      - name: Build Docker image
        run: docker compose build

      - name: Run Docker container
        run: docker compose up -d

      - name: Wait a bit for JMeter GUI to be ready (opcional)
        run: sleep 15

      - name: List running containers (debug)
        run: docker ps

      - name: Stop Docker container
        run: docker compose down
